name: Run PHPCS

on: [push]

jobs:
  test:
    name: WP ${{ matrix.wordpress }} on PHP ${{ matrix.php }}
    runs-on: ubuntu-16.04
    continue-on-error: ${{ matrix.allowed_failure }}
    
    env:
      WP_VERSION: ${{ matrix.wordpress }}
      
    strategy:
      fail-fast: false
      matrix:
        php: [ '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0' ]
        wordpress: [ '5.5', '5.6', '5.7'  ]
        allowed_failure: [ false ]
        include:
          # PHP nightly.
          - php: '8.1'
            wordpress: '5.7'
            allowed_failure: true
        # https://make.wordpress.org/core/2020/11/23/wordpress-and-php-8-0/
        exclude: 
          - php: '8.0'
            wordpress: '5.5'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          # https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php-extensions
          extensions: curl, dom, exif, fileinfo, hash, json, mbstring, mysqli, libsodium, openssl, pcre, imagick, xml, zip

      - name: Install Composer dependencies (PHP < 8.0 )
        if: ${{ matrix.php < 8.0 }}
        uses: ramsey/composer-install@v1

      - name: Install Composer dependencies (PHP >= 8.0)
        if: ${{ matrix.php >= 8.0 }}
        uses: ramsey/composer-install@v1
        with:
          composer-options: --ignore-platform-reqs

      - name: Show PHP version info
        run: php --version

      - name: Run PHPCS
        run: composer cs
